In [1]:
import torch

/Users/divyyadav/Desktop/pytorch/.venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:279: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [5]:
if torch.backends.mps.is_available():
    device = torch.device("mps")
    print('mps is there')
else:
    device = torch.device("cpu")

mps is there


In [ ]:
tensor=torch.Tensor([1,2,3])
tensor=tensor.to("mps")

tensor([1., 2., 3.], device='mps:0')

In [ ]:
tensor2 = torch.tensor([1, 2, 3,6,6,6,5])
tensor2 = tensor2.to("mps")
print(tensor2)

tensor([1, 2, 3, 6, 6, 6, 5], device='mps:0')


In [20]:
%%time
tensor2*tensor

CPU times: user 403 μs, sys: 252 μs, total: 655 μs
Wall time: 376 μs


tensor([ 1,  4,  9, 36, 36, 36, 25], device='mps:0')